//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MANTENIMIENTO : DbContext
    {
        public MANTENIMIENTO()
            : base("name=MANTENIMIENTO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Act_Man> Tb_Act_Man { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_DetalleFactura> Tb_DetalleFactura { get; set; }
        public virtual DbSet<Tb_Factura> Tb_Factura { get; set; }
        public virtual DbSet<Tb_Mant_Detalle> Tb_Mant_Detalle { get; set; }
        public virtual DbSet<Tb_Mantenimiento> Tb_Mantenimiento { get; set; }
        public virtual DbSet<Tb_Marca> Tb_Marca { get; set; }
        public virtual DbSet<Tb_Mecanico> Tb_Mecanico { get; set; }
        public virtual DbSet<Tb_Repuesto> Tb_Repuesto { get; set; }
        public virtual DbSet<Tb_Sist_Veh> Tb_Sist_Veh { get; set; }
        public virtual DbSet<Tb_Sub_Sist_Veh> Tb_Sub_Sist_Veh { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<Tb_Vehiculo> Tb_Vehiculo { get; set; }
    
        public virtual ObjectResult<usp_VehiculoFechas_Result> usp_VehiculoFechas(string idVehiculo, Nullable<System.DateTime> vFec_Inicio, Nullable<System.DateTime> vFec_Fin)
        {
            var idVehiculoParameter = idVehiculo != null ?
                new ObjectParameter("idVehiculo", idVehiculo) :
                new ObjectParameter("idVehiculo", typeof(string));
    
            var vFec_InicioParameter = vFec_Inicio.HasValue ?
                new ObjectParameter("vFec_Inicio", vFec_Inicio) :
                new ObjectParameter("vFec_Inicio", typeof(System.DateTime));
    
            var vFec_FinParameter = vFec_Fin.HasValue ?
                new ObjectParameter("vFec_Fin", vFec_Fin) :
                new ObjectParameter("vFec_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_VehiculoFechas_Result>("usp_VehiculoFechas", idVehiculoParameter, vFec_InicioParameter, vFec_FinParameter);
        }
    }
}
