//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cliente()
        {
            this.Tb_Factura = new HashSet<Tb_Factura>();
            this.Tb_Vehiculo = new HashSet<Tb_Vehiculo>();
        }
    
        public string idCliente { get; set; }
        public string cod_ubigeo { get; set; }
        public string Nom_cli { get; set; }
        public string Ape_cli { get; set; }
        public string dir_cli { get; set; }
        public string Ruc_Cli { get; set; }
        public string Telf_Cli { get; set; }
        public Nullable<System.DateTime> Fec_Nac_Cli { get; set; }
        public string Correo_Cli { get; set; }
        public string Sexo { get; set; }
        public string Raz_soc_cli { get; set; }
        public string Dni_Cli { get; set; }
        public Nullable<System.DateTime> Registro_Cliente { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<int> Est_Cli { get; set; }
        public Nullable<int> TipoCliente { get; set; }
    
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Factura> Tb_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Vehiculo> Tb_Vehiculo { get; set; }
    }
}
