//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Mecanico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Mecanico()
        {
            this.Tb_Mantenimiento = new HashSet<Tb_Mantenimiento>();
        }
    
        public string idMecanico { get; set; }
        public string cod_ubigeo { get; set; }
        public string Nom_mec { get; set; }
        public string Ape_mec { get; set; }
        public string Doc_Iden { get; set; }
        public string dir_mecanico { get; set; }
        public Nullable<System.DateTime> Fech_Ingreso { get; set; }
        public string Telf_Mec { get; set; }
        public Nullable<System.DateTime> Fec_Nac { get; set; }
        public string Sexo { get; set; }
        public byte[] Foto_Mec { get; set; }
        public string Espe_Mec { get; set; }
        public string Centro_Estudios { get; set; }
        public string Correo_Mec { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<int> Est_Mec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Mantenimiento> Tb_Mantenimiento { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
    }
}
