//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Mant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Vehiculo()
        {
            this.Tb_Mantenimiento = new HashSet<Tb_Mantenimiento>();
        }
    
        public string idVehiculo { get; set; }
        public string idCliente { get; set; }
        public Nullable<int> Act_kilom_Veh { get; set; }
        public Nullable<int> Act_Horom_Veh { get; set; }
        public string idMarca { get; set; }
        public Nullable<int> Tipo_Unidad { get; set; }
        public Nullable<System.DateTime> Fec_Ing_Veh { get; set; }
        public string Color { get; set; }
        public Nullable<int> Tipo_Trans { get; set; }
        public string Comentario { get; set; }
        public byte[] Foto_Veh { get; set; }
        public Nullable<int> Año_Modelo { get; set; }
        public string Modelo_Vehiculo { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Mantenimiento> Tb_Mantenimiento { get; set; }
        public virtual Tb_Marca Tb_Marca { get; set; }
    }
}
